package it.csi.gescovid.uscammgapi.business.be.impl.mapper.extended;

import java.util.List;

import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

import it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto.CovidusDFarmaco;
import it.csi.gescovid.uscammgapi.business.be.impl.mapper.generated.BaseCovidusDFarmacoMapper;

public interface FarmacoTipoMapper extends BaseCovidusDFarmacoMapper {
	
	
	@Select({ "select", " farm_id, farm_nome, farm_desc, farm_consenso_necessario, presc_tipo_id, utente_operazione, ",
		"validita_inizio, validita_fine, data_creazione, data_modifica, data_cancellazione ",
		"from covidus_d_farmaco " ,
		"where data_cancellazione is null and  now() between validita_inizio and coalesce(validita_fine, to_timestamp('01/01/2999','dd/mm/yyyy'))"})
	@Results({ @Result(column = "farm_id", property = "farmId", jdbcType = JdbcType.INTEGER, id = true),
		@Result(column = "farm_nome", property = "farmNome", jdbcType = JdbcType.VARCHAR),
		@Result(column = "farm_desc", property = "farmDesc", jdbcType = JdbcType.VARCHAR),
		@Result(column = "farm_consenso_necessario", property = "farmConsensoNecessario", jdbcType = JdbcType.BIT),
		@Result(column = "presc_tipo_id", property = "prescTipoId", jdbcType = JdbcType.INTEGER),
		@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
		@Result(column = "validita_inizio", property = "validitaInizio", jdbcType = JdbcType.TIMESTAMP),
		@Result(column = "validita_fine", property = "validitaFine", jdbcType = JdbcType.TIMESTAMP),
		@Result(column = "data_creazione", property = "dataCreazione", jdbcType = JdbcType.TIMESTAMP),
		@Result(column = "data_modifica", property = "dataModifica", jdbcType = JdbcType.TIMESTAMP),
		@Result(column = "data_cancellazione", property = "dataCancellazione", jdbcType = JdbcType.TIMESTAMP) })
	List<CovidusDFarmaco> selectAllFarmaciTipoValidi();
	
	
	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table covidus_d_farmaco
	 * @mbg.generated
	 */
	@Select({ "select", "farm_id, farm_nome, farm_desc, farm_consenso_necessario, presc_tipo_id, utente_operazione, ",
			"validita_inizio, validita_fine, data_creazione, data_modifica, data_cancellazione",
			"from covidus_d_farmaco", "where farm_id = #{farmId,jdbcType=INTEGER}" })
	@Results({ @Result(column = "farm_id", property = "farmId", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "farm_nome", property = "farmNome", jdbcType = JdbcType.VARCHAR),
			@Result(column = "farm_desc", property = "farmDesc", jdbcType = JdbcType.VARCHAR),
			@Result(column = "farm_consenso_necessario", property = "farmConsensoNecessario", jdbcType = JdbcType.BIT),
			@Result(column = "presc_tipo_id", property = "prescTipoId", jdbcType = JdbcType.INTEGER),
			@Result(column = "utente_operazione", property = "utenteOperazione", jdbcType = JdbcType.VARCHAR),
			@Result(column = "validita_inizio", property = "validitaInizio", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "validita_fine", property = "validitaFine", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_creazione", property = "dataCreazione", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_modifica", property = "dataModifica", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "data_cancellazione", property = "dataCancellazione", jdbcType = JdbcType.TIMESTAMP) })
	CovidusDFarmaco selectByFarmaid(Integer farmId);
	
	
	
	
}
