package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

public class Area {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.id_area
	 * @mbg.generated
	 */
	private Integer idArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.id_struttura
	 * @mbg.generated
	 */
	private String idStruttura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.id_d_area
	 * @mbg.generated
	 */
	private String idDArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.nome
	 * @mbg.generated
	 */
	private String nome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.responsabile
	 * @mbg.generated
	 */
	private String responsabile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.riferimento
	 * @mbg.generated
	 */
	private String riferimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.stato_validita
	 * @mbg.generated
	 */
	private String statoValidita;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.id_area
	 * @return  the value of area.id_area
	 * @mbg.generated
	 */
	public Integer getIdArea() {
		return idArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.id_area
	 * @param idArea  the value for area.id_area
	 * @mbg.generated
	 */
	public void setIdArea(Integer idArea) {
		this.idArea = idArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.id_struttura
	 * @return  the value of area.id_struttura
	 * @mbg.generated
	 */
	public String getIdStruttura() {
		return idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.id_struttura
	 * @param idStruttura  the value for area.id_struttura
	 * @mbg.generated
	 */
	public void setIdStruttura(String idStruttura) {
		this.idStruttura = idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.id_d_area
	 * @return  the value of area.id_d_area
	 * @mbg.generated
	 */
	public String getIdDArea() {
		return idDArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.id_d_area
	 * @param idDArea  the value for area.id_d_area
	 * @mbg.generated
	 */
	public void setIdDArea(String idDArea) {
		this.idDArea = idDArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.nome
	 * @return  the value of area.nome
	 * @mbg.generated
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.nome
	 * @param nome  the value for area.nome
	 * @mbg.generated
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.responsabile
	 * @return  the value of area.responsabile
	 * @mbg.generated
	 */
	public String getResponsabile() {
		return responsabile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.responsabile
	 * @param responsabile  the value for area.responsabile
	 * @mbg.generated
	 */
	public void setResponsabile(String responsabile) {
		this.responsabile = responsabile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.riferimento
	 * @return  the value of area.riferimento
	 * @mbg.generated
	 */
	public String getRiferimento() {
		return riferimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.riferimento
	 * @param riferimento  the value for area.riferimento
	 * @mbg.generated
	 */
	public void setRiferimento(String riferimento) {
		this.riferimento = riferimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.stato_validita
	 * @return  the value of area.stato_validita
	 * @mbg.generated
	 */
	public String getStatoValidita() {
		return statoValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.stato_validita
	 * @param statoValidita  the value for area.stato_validita
	 * @mbg.generated
	 */
	public void setStatoValidita(String statoValidita) {
		this.statoValidita = statoValidita;
	}
}