package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidusDSintomo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_sintomo.sin_id
	 * @mbg.generated
	 */
	private Integer sinId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_sintomo.sin_cod
	 * @mbg.generated
	 */
	private String sinCod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_sintomo.sin_desc
	 * @mbg.generated
	 */
	private String sinDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_sintomo.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_sintomo.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_sintomo.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_sintomo.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_sintomo.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_sintomo.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_sintomo.sin_misurabile
	 * @mbg.generated
	 */
	private Boolean sinMisurabile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_sintomo.sin_unita_misura
	 * @mbg.generated
	 */
	private String sinUnitaMisura;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_sintomo.sin_id
	 * @return  the value of covidus_d_sintomo.sin_id
	 * @mbg.generated
	 */
	public Integer getSinId() {
		return sinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_sintomo.sin_id
	 * @param sinId  the value for covidus_d_sintomo.sin_id
	 * @mbg.generated
	 */
	public void setSinId(Integer sinId) {
		this.sinId = sinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_sintomo.sin_cod
	 * @return  the value of covidus_d_sintomo.sin_cod
	 * @mbg.generated
	 */
	public String getSinCod() {
		return sinCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_sintomo.sin_cod
	 * @param sinCod  the value for covidus_d_sintomo.sin_cod
	 * @mbg.generated
	 */
	public void setSinCod(String sinCod) {
		this.sinCod = sinCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_sintomo.sin_desc
	 * @return  the value of covidus_d_sintomo.sin_desc
	 * @mbg.generated
	 */
	public String getSinDesc() {
		return sinDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_sintomo.sin_desc
	 * @param sinDesc  the value for covidus_d_sintomo.sin_desc
	 * @mbg.generated
	 */
	public void setSinDesc(String sinDesc) {
		this.sinDesc = sinDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_sintomo.utente_operazione
	 * @return  the value of covidus_d_sintomo.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_sintomo.utente_operazione
	 * @param utenteOperazione  the value for covidus_d_sintomo.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_sintomo.validita_inizio
	 * @return  the value of covidus_d_sintomo.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_sintomo.validita_inizio
	 * @param validitaInizio  the value for covidus_d_sintomo.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_sintomo.validita_fine
	 * @return  the value of covidus_d_sintomo.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_sintomo.validita_fine
	 * @param validitaFine  the value for covidus_d_sintomo.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_sintomo.data_creazione
	 * @return  the value of covidus_d_sintomo.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_sintomo.data_creazione
	 * @param dataCreazione  the value for covidus_d_sintomo.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_sintomo.data_modifica
	 * @return  the value of covidus_d_sintomo.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_sintomo.data_modifica
	 * @param dataModifica  the value for covidus_d_sintomo.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_sintomo.data_cancellazione
	 * @return  the value of covidus_d_sintomo.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_sintomo.data_cancellazione
	 * @param dataCancellazione  the value for covidus_d_sintomo.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_sintomo.sin_misurabile
	 * @return  the value of covidus_d_sintomo.sin_misurabile
	 * @mbg.generated
	 */
	public Boolean getSinMisurabile() {
		return sinMisurabile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_sintomo.sin_misurabile
	 * @param sinMisurabile  the value for covidus_d_sintomo.sin_misurabile
	 * @mbg.generated
	 */
	public void setSinMisurabile(Boolean sinMisurabile) {
		this.sinMisurabile = sinMisurabile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_sintomo.sin_unita_misura
	 * @return  the value of covidus_d_sintomo.sin_unita_misura
	 * @mbg.generated
	 */
	public String getSinUnitaMisura() {
		return sinUnitaMisura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_sintomo.sin_unita_misura
	 * @param sinUnitaMisura  the value for covidus_d_sintomo.sin_unita_misura
	 * @mbg.generated
	 */
	public void setSinUnitaMisura(String sinUnitaMisura) {
		this.sinUnitaMisura = sinUnitaMisura;
	}
}