package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidusDFarmaco {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_farmaco.farm_id
	 * @mbg.generated
	 */
	private Integer farmId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_farmaco.farm_nome
	 * @mbg.generated
	 */
	private String farmNome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_farmaco.farm_desc
	 * @mbg.generated
	 */
	private String farmDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_farmaco.farm_consenso_necessario
	 * @mbg.generated
	 */
	private Boolean farmConsensoNecessario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_farmaco.presc_tipo_id
	 * @mbg.generated
	 */
	private Integer prescTipoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_farmaco.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_farmaco.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_farmaco.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_farmaco.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_farmaco.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_farmaco.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_farmaco.farm_id
	 * @return  the value of covidus_d_farmaco.farm_id
	 * @mbg.generated
	 */
	public Integer getFarmId() {
		return farmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_farmaco.farm_id
	 * @param farmId  the value for covidus_d_farmaco.farm_id
	 * @mbg.generated
	 */
	public void setFarmId(Integer farmId) {
		this.farmId = farmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_farmaco.farm_nome
	 * @return  the value of covidus_d_farmaco.farm_nome
	 * @mbg.generated
	 */
	public String getFarmNome() {
		return farmNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_farmaco.farm_nome
	 * @param farmNome  the value for covidus_d_farmaco.farm_nome
	 * @mbg.generated
	 */
	public void setFarmNome(String farmNome) {
		this.farmNome = farmNome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_farmaco.farm_desc
	 * @return  the value of covidus_d_farmaco.farm_desc
	 * @mbg.generated
	 */
	public String getFarmDesc() {
		return farmDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_farmaco.farm_desc
	 * @param farmDesc  the value for covidus_d_farmaco.farm_desc
	 * @mbg.generated
	 */
	public void setFarmDesc(String farmDesc) {
		this.farmDesc = farmDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_farmaco.farm_consenso_necessario
	 * @return  the value of covidus_d_farmaco.farm_consenso_necessario
	 * @mbg.generated
	 */
	public Boolean getFarmConsensoNecessario() {
		return farmConsensoNecessario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_farmaco.farm_consenso_necessario
	 * @param farmConsensoNecessario  the value for covidus_d_farmaco.farm_consenso_necessario
	 * @mbg.generated
	 */
	public void setFarmConsensoNecessario(Boolean farmConsensoNecessario) {
		this.farmConsensoNecessario = farmConsensoNecessario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_farmaco.presc_tipo_id
	 * @return  the value of covidus_d_farmaco.presc_tipo_id
	 * @mbg.generated
	 */
	public Integer getPrescTipoId() {
		return prescTipoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_farmaco.presc_tipo_id
	 * @param prescTipoId  the value for covidus_d_farmaco.presc_tipo_id
	 * @mbg.generated
	 */
	public void setPrescTipoId(Integer prescTipoId) {
		this.prescTipoId = prescTipoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_farmaco.utente_operazione
	 * @return  the value of covidus_d_farmaco.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_farmaco.utente_operazione
	 * @param utenteOperazione  the value for covidus_d_farmaco.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_farmaco.validita_inizio
	 * @return  the value of covidus_d_farmaco.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_farmaco.validita_inizio
	 * @param validitaInizio  the value for covidus_d_farmaco.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_farmaco.validita_fine
	 * @return  the value of covidus_d_farmaco.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_farmaco.validita_fine
	 * @param validitaFine  the value for covidus_d_farmaco.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_farmaco.data_creazione
	 * @return  the value of covidus_d_farmaco.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_farmaco.data_creazione
	 * @param dataCreazione  the value for covidus_d_farmaco.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_farmaco.data_modifica
	 * @return  the value of covidus_d_farmaco.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_farmaco.data_modifica
	 * @param dataModifica  the value for covidus_d_farmaco.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_farmaco.data_cancellazione
	 * @return  the value of covidus_d_farmaco.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_farmaco.data_cancellazione
	 * @param dataCancellazione  the value for covidus_d_farmaco.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}