package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidusRInterventoFile {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_intervento_file.int_file_id
	 * @mbg.generated
	 */
	private Integer intFileId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_intervento_file.int_id
	 * @mbg.generated
	 */
	private Integer intId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_intervento_file.file_id
	 * @mbg.generated
	 */
	private Integer fileId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_intervento_file.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_intervento_file.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_intervento_file.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_intervento_file.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_intervento_file.int_file_id
	 * @return  the value of covidus_r_intervento_file.int_file_id
	 * @mbg.generated
	 */
	public Integer getIntFileId() {
		return intFileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_intervento_file.int_file_id
	 * @param intFileId  the value for covidus_r_intervento_file.int_file_id
	 * @mbg.generated
	 */
	public void setIntFileId(Integer intFileId) {
		this.intFileId = intFileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_intervento_file.int_id
	 * @return  the value of covidus_r_intervento_file.int_id
	 * @mbg.generated
	 */
	public Integer getIntId() {
		return intId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_intervento_file.int_id
	 * @param intId  the value for covidus_r_intervento_file.int_id
	 * @mbg.generated
	 */
	public void setIntId(Integer intId) {
		this.intId = intId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_intervento_file.file_id
	 * @return  the value of covidus_r_intervento_file.file_id
	 * @mbg.generated
	 */
	public Integer getFileId() {
		return fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_intervento_file.file_id
	 * @param fileId  the value for covidus_r_intervento_file.file_id
	 * @mbg.generated
	 */
	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_intervento_file.utente_operazione
	 * @return  the value of covidus_r_intervento_file.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_intervento_file.utente_operazione
	 * @param utenteOperazione  the value for covidus_r_intervento_file.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_intervento_file.data_creazione
	 * @return  the value of covidus_r_intervento_file.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_intervento_file.data_creazione
	 * @param dataCreazione  the value for covidus_r_intervento_file.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_intervento_file.data_modifica
	 * @return  the value of covidus_r_intervento_file.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_intervento_file.data_modifica
	 * @param dataModifica  the value for covidus_r_intervento_file.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_intervento_file.data_cancellazione
	 * @return  the value of covidus_r_intervento_file.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_intervento_file.data_cancellazione
	 * @param dataCancellazione  the value for covidus_r_intervento_file.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}