package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidusDSchedaStato {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_scheda_stato.sch_stato_id
	 * @mbg.generated
	 */
	private Integer schStatoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_scheda_stato.sch_stato_cod
	 * @mbg.generated
	 */
	private String schStatoCod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_scheda_stato.sch_stato_desc
	 * @mbg.generated
	 */
	private String schStatoDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_scheda_stato.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_scheda_stato.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_scheda_stato.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_scheda_stato.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_scheda_stato.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_scheda_stato.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_scheda_stato.sch_stato_id
	 * @return  the value of covidus_d_scheda_stato.sch_stato_id
	 * @mbg.generated
	 */
	public Integer getSchStatoId() {
		return schStatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_scheda_stato.sch_stato_id
	 * @param schStatoId  the value for covidus_d_scheda_stato.sch_stato_id
	 * @mbg.generated
	 */
	public void setSchStatoId(Integer schStatoId) {
		this.schStatoId = schStatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_scheda_stato.sch_stato_cod
	 * @return  the value of covidus_d_scheda_stato.sch_stato_cod
	 * @mbg.generated
	 */
	public String getSchStatoCod() {
		return schStatoCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_scheda_stato.sch_stato_cod
	 * @param schStatoCod  the value for covidus_d_scheda_stato.sch_stato_cod
	 * @mbg.generated
	 */
	public void setSchStatoCod(String schStatoCod) {
		this.schStatoCod = schStatoCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_scheda_stato.sch_stato_desc
	 * @return  the value of covidus_d_scheda_stato.sch_stato_desc
	 * @mbg.generated
	 */
	public String getSchStatoDesc() {
		return schStatoDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_scheda_stato.sch_stato_desc
	 * @param schStatoDesc  the value for covidus_d_scheda_stato.sch_stato_desc
	 * @mbg.generated
	 */
	public void setSchStatoDesc(String schStatoDesc) {
		this.schStatoDesc = schStatoDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_scheda_stato.validita_inizio
	 * @return  the value of covidus_d_scheda_stato.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_scheda_stato.validita_inizio
	 * @param validitaInizio  the value for covidus_d_scheda_stato.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_scheda_stato.validita_fine
	 * @return  the value of covidus_d_scheda_stato.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_scheda_stato.validita_fine
	 * @param validitaFine  the value for covidus_d_scheda_stato.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_scheda_stato.utente_operazione
	 * @return  the value of covidus_d_scheda_stato.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_scheda_stato.utente_operazione
	 * @param utenteOperazione  the value for covidus_d_scheda_stato.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_scheda_stato.data_creazione
	 * @return  the value of covidus_d_scheda_stato.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_scheda_stato.data_creazione
	 * @param dataCreazione  the value for covidus_d_scheda_stato.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_scheda_stato.data_modifica
	 * @return  the value of covidus_d_scheda_stato.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_scheda_stato.data_modifica
	 * @param dataModifica  the value for covidus_d_scheda_stato.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_scheda_stato.data_cancellazione
	 * @return  the value of covidus_d_scheda_stato.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_scheda_stato.data_cancellazione
	 * @param dataCancellazione  the value for covidus_d_scheda_stato.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}