package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;
import java.math.BigDecimal;

public class CovidusRDiarioDetSintomo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_diario_det_sintomo.diadetsin_id
	 * @mbg.generated
	 */
	private Integer diadetsinId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_diario_det_sintomo.diadet_id
	 * @mbg.generated
	 */
	private Integer diadetId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_diario_det_sintomo.sin_id
	 * @mbg.generated
	 */
	private Integer sinId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_diario_det_sintomo.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_diario_det_sintomo.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_diario_det_sintomo.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_diario_det_sintomo.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_diario_det_sintomo.id_profilo_operazione
	 * @mbg.generated
	 */
	private Integer idProfiloOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_diario_det_sintomo.sin_note
	 * @mbg.generated
	 */
	private String sinNote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_diario_det_sintomo.sin_valore
	 * @mbg.generated
	 */
	private BigDecimal sinValore;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_diario_det_sintomo.diadetsin_id
	 * @return  the value of covidus_r_diario_det_sintomo.diadetsin_id
	 * @mbg.generated
	 */
	public Integer getDiadetsinId() {
		return diadetsinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_diario_det_sintomo.diadetsin_id
	 * @param diadetsinId  the value for covidus_r_diario_det_sintomo.diadetsin_id
	 * @mbg.generated
	 */
	public void setDiadetsinId(Integer diadetsinId) {
		this.diadetsinId = diadetsinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_diario_det_sintomo.diadet_id
	 * @return  the value of covidus_r_diario_det_sintomo.diadet_id
	 * @mbg.generated
	 */
	public Integer getDiadetId() {
		return diadetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_diario_det_sintomo.diadet_id
	 * @param diadetId  the value for covidus_r_diario_det_sintomo.diadet_id
	 * @mbg.generated
	 */
	public void setDiadetId(Integer diadetId) {
		this.diadetId = diadetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_diario_det_sintomo.sin_id
	 * @return  the value of covidus_r_diario_det_sintomo.sin_id
	 * @mbg.generated
	 */
	public Integer getSinId() {
		return sinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_diario_det_sintomo.sin_id
	 * @param sinId  the value for covidus_r_diario_det_sintomo.sin_id
	 * @mbg.generated
	 */
	public void setSinId(Integer sinId) {
		this.sinId = sinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_diario_det_sintomo.utente_operazione
	 * @return  the value of covidus_r_diario_det_sintomo.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_diario_det_sintomo.utente_operazione
	 * @param utenteOperazione  the value for covidus_r_diario_det_sintomo.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_diario_det_sintomo.data_creazione
	 * @return  the value of covidus_r_diario_det_sintomo.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_diario_det_sintomo.data_creazione
	 * @param dataCreazione  the value for covidus_r_diario_det_sintomo.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_diario_det_sintomo.data_modifica
	 * @return  the value of covidus_r_diario_det_sintomo.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_diario_det_sintomo.data_modifica
	 * @param dataModifica  the value for covidus_r_diario_det_sintomo.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_diario_det_sintomo.data_cancellazione
	 * @return  the value of covidus_r_diario_det_sintomo.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_diario_det_sintomo.data_cancellazione
	 * @param dataCancellazione  the value for covidus_r_diario_det_sintomo.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_diario_det_sintomo.id_profilo_operazione
	 * @return  the value of covidus_r_diario_det_sintomo.id_profilo_operazione
	 * @mbg.generated
	 */
	public Integer getIdProfiloOperazione() {
		return idProfiloOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_diario_det_sintomo.id_profilo_operazione
	 * @param idProfiloOperazione  the value for covidus_r_diario_det_sintomo.id_profilo_operazione
	 * @mbg.generated
	 */
	public void setIdProfiloOperazione(Integer idProfiloOperazione) {
		this.idProfiloOperazione = idProfiloOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_diario_det_sintomo.sin_note
	 * @return  the value of covidus_r_diario_det_sintomo.sin_note
	 * @mbg.generated
	 */
	public String getSinNote() {
		return sinNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_diario_det_sintomo.sin_note
	 * @param sinNote  the value for covidus_r_diario_det_sintomo.sin_note
	 * @mbg.generated
	 */
	public void setSinNote(String sinNote) {
		this.sinNote = sinNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_diario_det_sintomo.sin_valore
	 * @return  the value of covidus_r_diario_det_sintomo.sin_valore
	 * @mbg.generated
	 */
	public BigDecimal getSinValore() {
		return sinValore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_diario_det_sintomo.sin_valore
	 * @param sinValore  the value for covidus_r_diario_det_sintomo.sin_valore
	 * @mbg.generated
	 */
	public void setSinValore(BigDecimal sinValore) {
		this.sinValore = sinValore;
	}
}