package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidusRAppStruttura {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_app_struttura.appstr_id
	 * @mbg.generated
	 */
	private Integer appstrId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_app_struttura.app_id
	 * @mbg.generated
	 */
	private Integer appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_app_struttura.id_struttura
	 * @mbg.generated
	 */
	private String idStruttura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_app_struttura.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_app_struttura.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_app_struttura.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_app_struttura.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_app_struttura.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_app_struttura.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_app_struttura.appstr_id
	 * @return  the value of covidus_r_app_struttura.appstr_id
	 * @mbg.generated
	 */
	public Integer getAppstrId() {
		return appstrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_app_struttura.appstr_id
	 * @param appstrId  the value for covidus_r_app_struttura.appstr_id
	 * @mbg.generated
	 */
	public void setAppstrId(Integer appstrId) {
		this.appstrId = appstrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_app_struttura.app_id
	 * @return  the value of covidus_r_app_struttura.app_id
	 * @mbg.generated
	 */
	public Integer getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_app_struttura.app_id
	 * @param appId  the value for covidus_r_app_struttura.app_id
	 * @mbg.generated
	 */
	public void setAppId(Integer appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_app_struttura.id_struttura
	 * @return  the value of covidus_r_app_struttura.id_struttura
	 * @mbg.generated
	 */
	public String getIdStruttura() {
		return idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_app_struttura.id_struttura
	 * @param idStruttura  the value for covidus_r_app_struttura.id_struttura
	 * @mbg.generated
	 */
	public void setIdStruttura(String idStruttura) {
		this.idStruttura = idStruttura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_app_struttura.validita_inizio
	 * @return  the value of covidus_r_app_struttura.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_app_struttura.validita_inizio
	 * @param validitaInizio  the value for covidus_r_app_struttura.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_app_struttura.validita_fine
	 * @return  the value of covidus_r_app_struttura.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_app_struttura.validita_fine
	 * @param validitaFine  the value for covidus_r_app_struttura.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_app_struttura.utente_operazione
	 * @return  the value of covidus_r_app_struttura.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_app_struttura.utente_operazione
	 * @param utenteOperazione  the value for covidus_r_app_struttura.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_app_struttura.data_creazione
	 * @return  the value of covidus_r_app_struttura.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_app_struttura.data_creazione
	 * @param dataCreazione  the value for covidus_r_app_struttura.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_app_struttura.data_modifica
	 * @return  the value of covidus_r_app_struttura.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_app_struttura.data_modifica
	 * @param dataModifica  the value for covidus_r_app_struttura.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_app_struttura.data_cancellazione
	 * @return  the value of covidus_r_app_struttura.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_app_struttura.data_cancellazione
	 * @param dataCancellazione  the value for covidus_r_app_struttura.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}