package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidDApplicativo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covid_d_applicativo.app_id
	 * @mbg.generated
	 */
	private Integer appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covid_d_applicativo.app_cod
	 * @mbg.generated
	 */
	private String appCod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covid_d_applicativo.app_desc
	 * @mbg.generated
	 */
	private String appDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covid_d_applicativo.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covid_d_applicativo.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covid_d_applicativo.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covid_d_applicativo.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covid_d_applicativo.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covid_d_applicativo.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covid_d_applicativo.app_id
	 * @return  the value of covid_d_applicativo.app_id
	 * @mbg.generated
	 */
	public Integer getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covid_d_applicativo.app_id
	 * @param appId  the value for covid_d_applicativo.app_id
	 * @mbg.generated
	 */
	public void setAppId(Integer appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covid_d_applicativo.app_cod
	 * @return  the value of covid_d_applicativo.app_cod
	 * @mbg.generated
	 */
	public String getAppCod() {
		return appCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covid_d_applicativo.app_cod
	 * @param appCod  the value for covid_d_applicativo.app_cod
	 * @mbg.generated
	 */
	public void setAppCod(String appCod) {
		this.appCod = appCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covid_d_applicativo.app_desc
	 * @return  the value of covid_d_applicativo.app_desc
	 * @mbg.generated
	 */
	public String getAppDesc() {
		return appDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covid_d_applicativo.app_desc
	 * @param appDesc  the value for covid_d_applicativo.app_desc
	 * @mbg.generated
	 */
	public void setAppDesc(String appDesc) {
		this.appDesc = appDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covid_d_applicativo.validita_inizio
	 * @return  the value of covid_d_applicativo.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covid_d_applicativo.validita_inizio
	 * @param validitaInizio  the value for covid_d_applicativo.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covid_d_applicativo.validita_fine
	 * @return  the value of covid_d_applicativo.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covid_d_applicativo.validita_fine
	 * @param validitaFine  the value for covid_d_applicativo.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covid_d_applicativo.data_creazione
	 * @return  the value of covid_d_applicativo.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covid_d_applicativo.data_creazione
	 * @param dataCreazione  the value for covid_d_applicativo.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covid_d_applicativo.data_modifica
	 * @return  the value of covid_d_applicativo.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covid_d_applicativo.data_modifica
	 * @param dataModifica  the value for covid_d_applicativo.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covid_d_applicativo.data_cancellazione
	 * @return  the value of covid_d_applicativo.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covid_d_applicativo.data_cancellazione
	 * @param dataCancellazione  the value for covid_d_applicativo.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covid_d_applicativo.utente_operazione
	 * @return  the value of covid_d_applicativo.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covid_d_applicativo.utente_operazione
	 * @param utenteOperazione  the value for covid_d_applicativo.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}
}