package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidusRConsensoFarmacoFile {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_consenso_farmaco_file.consfarm_file_id
	 * @mbg.generated
	 */
	private Integer consfarmFileId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_consenso_farmaco_file.consfarm_id
	 * @mbg.generated
	 */
	private Integer consfarmId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_consenso_farmaco_file.file_id
	 * @mbg.generated
	 */
	private Integer fileId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_consenso_farmaco_file.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_consenso_farmaco_file.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_consenso_farmaco_file.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_consenso_farmaco_file.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_consenso_farmaco_file.consfarm_file_id
	 * @return  the value of covidus_r_consenso_farmaco_file.consfarm_file_id
	 * @mbg.generated
	 */
	public Integer getConsfarmFileId() {
		return consfarmFileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_consenso_farmaco_file.consfarm_file_id
	 * @param consfarmFileId  the value for covidus_r_consenso_farmaco_file.consfarm_file_id
	 * @mbg.generated
	 */
	public void setConsfarmFileId(Integer consfarmFileId) {
		this.consfarmFileId = consfarmFileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_consenso_farmaco_file.consfarm_id
	 * @return  the value of covidus_r_consenso_farmaco_file.consfarm_id
	 * @mbg.generated
	 */
	public Integer getConsfarmId() {
		return consfarmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_consenso_farmaco_file.consfarm_id
	 * @param consfarmId  the value for covidus_r_consenso_farmaco_file.consfarm_id
	 * @mbg.generated
	 */
	public void setConsfarmId(Integer consfarmId) {
		this.consfarmId = consfarmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_consenso_farmaco_file.file_id
	 * @return  the value of covidus_r_consenso_farmaco_file.file_id
	 * @mbg.generated
	 */
	public Integer getFileId() {
		return fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_consenso_farmaco_file.file_id
	 * @param fileId  the value for covidus_r_consenso_farmaco_file.file_id
	 * @mbg.generated
	 */
	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_consenso_farmaco_file.utente_operazione
	 * @return  the value of covidus_r_consenso_farmaco_file.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_consenso_farmaco_file.utente_operazione
	 * @param utenteOperazione  the value for covidus_r_consenso_farmaco_file.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_consenso_farmaco_file.data_creazione
	 * @return  the value of covidus_r_consenso_farmaco_file.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_consenso_farmaco_file.data_creazione
	 * @param dataCreazione  the value for covidus_r_consenso_farmaco_file.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_consenso_farmaco_file.data_modifica
	 * @return  the value of covidus_r_consenso_farmaco_file.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_consenso_farmaco_file.data_modifica
	 * @param dataModifica  the value for covidus_r_consenso_farmaco_file.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_consenso_farmaco_file.data_cancellazione
	 * @return  the value of covidus_r_consenso_farmaco_file.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_consenso_farmaco_file.data_cancellazione
	 * @param dataCancellazione  the value for covidus_r_consenso_farmaco_file.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}