package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidusDConsensoTipo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_consenso_tipo.cons_tipo_id
	 * @mbg.generated
	 */
	private Integer consTipoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_consenso_tipo.cons_tipo_cod
	 * @mbg.generated
	 */
	private String consTipoCod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_consenso_tipo.cons_tipo_desc
	 * @mbg.generated
	 */
	private String consTipoDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_consenso_tipo.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_consenso_tipo.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_consenso_tipo.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_consenso_tipo.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_consenso_tipo.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_d_consenso_tipo.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_consenso_tipo.cons_tipo_id
	 * @return  the value of covidus_d_consenso_tipo.cons_tipo_id
	 * @mbg.generated
	 */
	public Integer getConsTipoId() {
		return consTipoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_consenso_tipo.cons_tipo_id
	 * @param consTipoId  the value for covidus_d_consenso_tipo.cons_tipo_id
	 * @mbg.generated
	 */
	public void setConsTipoId(Integer consTipoId) {
		this.consTipoId = consTipoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_consenso_tipo.cons_tipo_cod
	 * @return  the value of covidus_d_consenso_tipo.cons_tipo_cod
	 * @mbg.generated
	 */
	public String getConsTipoCod() {
		return consTipoCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_consenso_tipo.cons_tipo_cod
	 * @param consTipoCod  the value for covidus_d_consenso_tipo.cons_tipo_cod
	 * @mbg.generated
	 */
	public void setConsTipoCod(String consTipoCod) {
		this.consTipoCod = consTipoCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_consenso_tipo.cons_tipo_desc
	 * @return  the value of covidus_d_consenso_tipo.cons_tipo_desc
	 * @mbg.generated
	 */
	public String getConsTipoDesc() {
		return consTipoDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_consenso_tipo.cons_tipo_desc
	 * @param consTipoDesc  the value for covidus_d_consenso_tipo.cons_tipo_desc
	 * @mbg.generated
	 */
	public void setConsTipoDesc(String consTipoDesc) {
		this.consTipoDesc = consTipoDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_consenso_tipo.validita_inizio
	 * @return  the value of covidus_d_consenso_tipo.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_consenso_tipo.validita_inizio
	 * @param validitaInizio  the value for covidus_d_consenso_tipo.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_consenso_tipo.validita_fine
	 * @return  the value of covidus_d_consenso_tipo.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_consenso_tipo.validita_fine
	 * @param validitaFine  the value for covidus_d_consenso_tipo.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_consenso_tipo.utente_operazione
	 * @return  the value of covidus_d_consenso_tipo.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_consenso_tipo.utente_operazione
	 * @param utenteOperazione  the value for covidus_d_consenso_tipo.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_consenso_tipo.data_creazione
	 * @return  the value of covidus_d_consenso_tipo.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_consenso_tipo.data_creazione
	 * @param dataCreazione  the value for covidus_d_consenso_tipo.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_consenso_tipo.data_modifica
	 * @return  the value of covidus_d_consenso_tipo.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_consenso_tipo.data_modifica
	 * @param dataModifica  the value for covidus_d_consenso_tipo.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_d_consenso_tipo.data_cancellazione
	 * @return  the value of covidus_d_consenso_tipo.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_d_consenso_tipo.data_cancellazione
	 * @param dataCancellazione  the value for covidus_d_consenso_tipo.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}