package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidusRSchedaStato {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_scheda_stato.scar_stato_id
	 * @mbg.generated
	 */
	private Integer scarStatoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_scheda_stato.sch_id
	 * @mbg.generated
	 */
	private Integer schId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_scheda_stato.sch_stato_id
	 * @mbg.generated
	 */
	private Integer schStatoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_scheda_stato.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_scheda_stato.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_scheda_stato.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_scheda_stato.id_profilo_operazione
	 * @mbg.generated
	 */
	private Integer idProfiloOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_scheda_stato.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_scheda_stato.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_r_scheda_stato.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_scheda_stato.scar_stato_id
	 * @return  the value of covidus_r_scheda_stato.scar_stato_id
	 * @mbg.generated
	 */
	public Integer getScarStatoId() {
		return scarStatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_scheda_stato.scar_stato_id
	 * @param scarStatoId  the value for covidus_r_scheda_stato.scar_stato_id
	 * @mbg.generated
	 */
	public void setScarStatoId(Integer scarStatoId) {
		this.scarStatoId = scarStatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_scheda_stato.sch_id
	 * @return  the value of covidus_r_scheda_stato.sch_id
	 * @mbg.generated
	 */
	public Integer getSchId() {
		return schId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_scheda_stato.sch_id
	 * @param schId  the value for covidus_r_scheda_stato.sch_id
	 * @mbg.generated
	 */
	public void setSchId(Integer schId) {
		this.schId = schId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_scheda_stato.sch_stato_id
	 * @return  the value of covidus_r_scheda_stato.sch_stato_id
	 * @mbg.generated
	 */
	public Integer getSchStatoId() {
		return schStatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_scheda_stato.sch_stato_id
	 * @param schStatoId  the value for covidus_r_scheda_stato.sch_stato_id
	 * @mbg.generated
	 */
	public void setSchStatoId(Integer schStatoId) {
		this.schStatoId = schStatoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_scheda_stato.validita_inizio
	 * @return  the value of covidus_r_scheda_stato.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_scheda_stato.validita_inizio
	 * @param validitaInizio  the value for covidus_r_scheda_stato.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_scheda_stato.validita_fine
	 * @return  the value of covidus_r_scheda_stato.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_scheda_stato.validita_fine
	 * @param validitaFine  the value for covidus_r_scheda_stato.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_scheda_stato.utente_operazione
	 * @return  the value of covidus_r_scheda_stato.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_scheda_stato.utente_operazione
	 * @param utenteOperazione  the value for covidus_r_scheda_stato.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_scheda_stato.id_profilo_operazione
	 * @return  the value of covidus_r_scheda_stato.id_profilo_operazione
	 * @mbg.generated
	 */
	public Integer getIdProfiloOperazione() {
		return idProfiloOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_scheda_stato.id_profilo_operazione
	 * @param idProfiloOperazione  the value for covidus_r_scheda_stato.id_profilo_operazione
	 * @mbg.generated
	 */
	public void setIdProfiloOperazione(Integer idProfiloOperazione) {
		this.idProfiloOperazione = idProfiloOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_scheda_stato.data_creazione
	 * @return  the value of covidus_r_scheda_stato.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_scheda_stato.data_creazione
	 * @param dataCreazione  the value for covidus_r_scheda_stato.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_scheda_stato.data_modifica
	 * @return  the value of covidus_r_scheda_stato.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_scheda_stato.data_modifica
	 * @param dataModifica  the value for covidus_r_scheda_stato.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_r_scheda_stato.data_cancellazione
	 * @return  the value of covidus_r_scheda_stato.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_r_scheda_stato.data_cancellazione
	 * @param dataCancellazione  the value for covidus_r_scheda_stato.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}