package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidusTAdiCovidDet {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_adicovid_det.adicovid_det_id
	 * @mbg.generated
	 */
	private Integer adicovidDetId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_adicovid_det.adicovid_det_data
	 * @mbg.generated
	 */
	private Date adicovidDetData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_adicovid_det.adicovid_det_note
	 * @mbg.generated
	 */
	private String adicovidDetNote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_adicovid_det.adicovid_id
	 * @mbg.generated
	 */
	private Integer adicovidId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_adicovid_det.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_adicovid_det.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_adicovid_det.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_adicovid_det.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_adicovid_det.adicovid_det_id
	 * @return  the value of covidus_t_adicovid_det.adicovid_det_id
	 * @mbg.generated
	 */
	public Integer getAdicovidDetId() {
		return adicovidDetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_adicovid_det.adicovid_det_id
	 * @param adicovidDetId  the value for covidus_t_adicovid_det.adicovid_det_id
	 * @mbg.generated
	 */
	public void setAdicovidDetId(Integer adicovidDetId) {
		this.adicovidDetId = adicovidDetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_adicovid_det.adicovid_det_data
	 * @return  the value of covidus_t_adicovid_det.adicovid_det_data
	 * @mbg.generated
	 */
	public Date getAdicovidDetData() {
		return adicovidDetData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_adicovid_det.adicovid_det_data
	 * @param adicovidDetData  the value for covidus_t_adicovid_det.adicovid_det_data
	 * @mbg.generated
	 */
	public void setAdicovidDetData(Date adicovidDetData) {
		this.adicovidDetData = adicovidDetData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_adicovid_det.adicovid_det_note
	 * @return  the value of covidus_t_adicovid_det.adicovid_det_note
	 * @mbg.generated
	 */
	public String getAdicovidDetNote() {
		return adicovidDetNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_adicovid_det.adicovid_det_note
	 * @param adicovidDetNote  the value for covidus_t_adicovid_det.adicovid_det_note
	 * @mbg.generated
	 */
	public void setAdicovidDetNote(String adicovidDetNote) {
		this.adicovidDetNote = adicovidDetNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_adicovid_det.adicovid_id
	 * @return  the value of covidus_t_adicovid_det.adicovid_id
	 * @mbg.generated
	 */
	public Integer getAdicovidId() {
		return adicovidId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_adicovid_det.adicovid_id
	 * @param adicovidId  the value for covidus_t_adicovid_det.adicovid_id
	 * @mbg.generated
	 */
	public void setAdicovidId(Integer adicovidId) {
		this.adicovidId = adicovidId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_adicovid_det.utente_operazione
	 * @return  the value of covidus_t_adicovid_det.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_adicovid_det.utente_operazione
	 * @param utenteOperazione  the value for covidus_t_adicovid_det.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_adicovid_det.data_creazione
	 * @return  the value of covidus_t_adicovid_det.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_adicovid_det.data_creazione
	 * @param dataCreazione  the value for covidus_t_adicovid_det.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_adicovid_det.data_modifica
	 * @return  the value of covidus_t_adicovid_det.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_adicovid_det.data_modifica
	 * @param dataModifica  the value for covidus_t_adicovid_det.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_adicovid_det.data_cancellazione
	 * @return  the value of covidus_t_adicovid_det.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_adicovid_det.data_cancellazione
	 * @param dataCancellazione  the value for covidus_t_adicovid_det.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}