package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidusTDiarioDet {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_diario_det.diadet_id
	 * @mbg.generated
	 */
	private Integer diadetId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_diario_det.diadet_data
	 * @mbg.generated
	 */
	private Date diadetData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_diario_det.diadet_note
	 * @mbg.generated
	 */
	private String diadetNote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_diario_det.dia_id
	 * @mbg.generated
	 */
	private Integer diaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_diario_det.int_id
	 * @mbg.generated
	 */
	private Integer intId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_diario_det.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_diario_det.id_profilo_operazione
	 * @mbg.generated
	 */
	private Integer idProfiloOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_diario_det.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_diario_det.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_diario_det.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_diario_det.is_adi_covid
	 * @mbg.generated
	 */
	private Boolean isAdiCovid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_diario_det.data_adi_covid
	 * @mbg.generated
	 */
	private Date dataAdiCovid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_diario_det.note_adi_covid
	 * @mbg.generated
	 */
	private String noteAdiCovid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_diario_det.adicovid_id
	 * @mbg.generated
	 */
	private Integer adicovidId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_diario_det.diadet_id
	 * @return  the value of covidus_t_diario_det.diadet_id
	 * @mbg.generated
	 */
	public Integer getDiadetId() {
		return diadetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_diario_det.diadet_id
	 * @param diadetId  the value for covidus_t_diario_det.diadet_id
	 * @mbg.generated
	 */
	public void setDiadetId(Integer diadetId) {
		this.diadetId = diadetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_diario_det.diadet_data
	 * @return  the value of covidus_t_diario_det.diadet_data
	 * @mbg.generated
	 */
	public Date getDiadetData() {
		return diadetData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_diario_det.diadet_data
	 * @param diadetData  the value for covidus_t_diario_det.diadet_data
	 * @mbg.generated
	 */
	public void setDiadetData(Date diadetData) {
		this.diadetData = diadetData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_diario_det.diadet_note
	 * @return  the value of covidus_t_diario_det.diadet_note
	 * @mbg.generated
	 */
	public String getDiadetNote() {
		return diadetNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_diario_det.diadet_note
	 * @param diadetNote  the value for covidus_t_diario_det.diadet_note
	 * @mbg.generated
	 */
	public void setDiadetNote(String diadetNote) {
		this.diadetNote = diadetNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_diario_det.dia_id
	 * @return  the value of covidus_t_diario_det.dia_id
	 * @mbg.generated
	 */
	public Integer getDiaId() {
		return diaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_diario_det.dia_id
	 * @param diaId  the value for covidus_t_diario_det.dia_id
	 * @mbg.generated
	 */
	public void setDiaId(Integer diaId) {
		this.diaId = diaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_diario_det.int_id
	 * @return  the value of covidus_t_diario_det.int_id
	 * @mbg.generated
	 */
	public Integer getIntId() {
		return intId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_diario_det.int_id
	 * @param intId  the value for covidus_t_diario_det.int_id
	 * @mbg.generated
	 */
	public void setIntId(Integer intId) {
		this.intId = intId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_diario_det.utente_operazione
	 * @return  the value of covidus_t_diario_det.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_diario_det.utente_operazione
	 * @param utenteOperazione  the value for covidus_t_diario_det.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_diario_det.id_profilo_operazione
	 * @return  the value of covidus_t_diario_det.id_profilo_operazione
	 * @mbg.generated
	 */
	public Integer getIdProfiloOperazione() {
		return idProfiloOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_diario_det.id_profilo_operazione
	 * @param idProfiloOperazione  the value for covidus_t_diario_det.id_profilo_operazione
	 * @mbg.generated
	 */
	public void setIdProfiloOperazione(Integer idProfiloOperazione) {
		this.idProfiloOperazione = idProfiloOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_diario_det.data_creazione
	 * @return  the value of covidus_t_diario_det.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_diario_det.data_creazione
	 * @param dataCreazione  the value for covidus_t_diario_det.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_diario_det.data_modifica
	 * @return  the value of covidus_t_diario_det.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_diario_det.data_modifica
	 * @param dataModifica  the value for covidus_t_diario_det.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_diario_det.data_cancellazione
	 * @return  the value of covidus_t_diario_det.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_diario_det.data_cancellazione
	 * @param dataCancellazione  the value for covidus_t_diario_det.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_diario_det.is_adi_covid
	 * @return  the value of covidus_t_diario_det.is_adi_covid
	 * @mbg.generated
	 */
	public Boolean getIsAdiCovid() {
		return isAdiCovid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_diario_det.is_adi_covid
	 * @param isAdiCovid  the value for covidus_t_diario_det.is_adi_covid
	 * @mbg.generated
	 */
	public void setIsAdiCovid(Boolean isAdiCovid) {
		this.isAdiCovid = isAdiCovid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_diario_det.data_adi_covid
	 * @return  the value of covidus_t_diario_det.data_adi_covid
	 * @mbg.generated
	 */
	public Date getDataAdiCovid() {
		return dataAdiCovid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_diario_det.data_adi_covid
	 * @param dataAdiCovid  the value for covidus_t_diario_det.data_adi_covid
	 * @mbg.generated
	 */
	public void setDataAdiCovid(Date dataAdiCovid) {
		this.dataAdiCovid = dataAdiCovid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_diario_det.note_adi_covid
	 * @return  the value of covidus_t_diario_det.note_adi_covid
	 * @mbg.generated
	 */
	public String getNoteAdiCovid() {
		return noteAdiCovid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_diario_det.note_adi_covid
	 * @param noteAdiCovid  the value for covidus_t_diario_det.note_adi_covid
	 * @mbg.generated
	 */
	public void setNoteAdiCovid(String noteAdiCovid) {
		this.noteAdiCovid = noteAdiCovid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_diario_det.adicovid_id
	 * @return  the value of covidus_t_diario_det.adicovid_id
	 * @mbg.generated
	 */
	public Integer getAdicovidId() {
		return adicovidId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_diario_det.adicovid_id
	 * @param adicovidId  the value for covidus_t_diario_det.adicovid_id
	 * @mbg.generated
	 */
	public void setAdicovidId(Integer adicovidId) {
		this.adicovidId = adicovidId;
	}
}