package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidusTIntervento {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_intervento.int_id
	 * @mbg.generated
	 */
	private Integer intId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_intervento.int_data
	 * @mbg.generated
	 */
	private Date intData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_intervento.int_desc
	 * @mbg.generated
	 */
	private String intDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_intervento.int_azione_intrapresa
	 * @mbg.generated
	 */
	private String intAzioneIntrapresa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_intervento.sch_id
	 * @mbg.generated
	 */
	private Integer schId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_intervento.int_tipo_id
	 * @mbg.generated
	 */
	private Integer intTipoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_intervento.az_id
	 * @mbg.generated
	 */
	private Integer azId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_intervento.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_intervento.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_intervento.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_intervento.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_intervento.int_id
	 * @return  the value of covidus_t_intervento.int_id
	 * @mbg.generated
	 */
	public Integer getIntId() {
		return intId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_intervento.int_id
	 * @param intId  the value for covidus_t_intervento.int_id
	 * @mbg.generated
	 */
	public void setIntId(Integer intId) {
		this.intId = intId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_intervento.int_data
	 * @return  the value of covidus_t_intervento.int_data
	 * @mbg.generated
	 */
	public Date getIntData() {
		return intData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_intervento.int_data
	 * @param intData  the value for covidus_t_intervento.int_data
	 * @mbg.generated
	 */
	public void setIntData(Date intData) {
		this.intData = intData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_intervento.int_desc
	 * @return  the value of covidus_t_intervento.int_desc
	 * @mbg.generated
	 */
	public String getIntDesc() {
		return intDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_intervento.int_desc
	 * @param intDesc  the value for covidus_t_intervento.int_desc
	 * @mbg.generated
	 */
	public void setIntDesc(String intDesc) {
		this.intDesc = intDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_intervento.int_azione_intrapresa
	 * @return  the value of covidus_t_intervento.int_azione_intrapresa
	 * @mbg.generated
	 */
	public String getIntAzioneIntrapresa() {
		return intAzioneIntrapresa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_intervento.int_azione_intrapresa
	 * @param intAzioneIntrapresa  the value for covidus_t_intervento.int_azione_intrapresa
	 * @mbg.generated
	 */
	public void setIntAzioneIntrapresa(String intAzioneIntrapresa) {
		this.intAzioneIntrapresa = intAzioneIntrapresa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_intervento.sch_id
	 * @return  the value of covidus_t_intervento.sch_id
	 * @mbg.generated
	 */
	public Integer getSchId() {
		return schId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_intervento.sch_id
	 * @param schId  the value for covidus_t_intervento.sch_id
	 * @mbg.generated
	 */
	public void setSchId(Integer schId) {
		this.schId = schId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_intervento.int_tipo_id
	 * @return  the value of covidus_t_intervento.int_tipo_id
	 * @mbg.generated
	 */
	public Integer getIntTipoId() {
		return intTipoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_intervento.int_tipo_id
	 * @param intTipoId  the value for covidus_t_intervento.int_tipo_id
	 * @mbg.generated
	 */
	public void setIntTipoId(Integer intTipoId) {
		this.intTipoId = intTipoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_intervento.az_id
	 * @return  the value of covidus_t_intervento.az_id
	 * @mbg.generated
	 */
	public Integer getAzId() {
		return azId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_intervento.az_id
	 * @param azId  the value for covidus_t_intervento.az_id
	 * @mbg.generated
	 */
	public void setAzId(Integer azId) {
		this.azId = azId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_intervento.utente_operazione
	 * @return  the value of covidus_t_intervento.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_intervento.utente_operazione
	 * @param utenteOperazione  the value for covidus_t_intervento.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_intervento.data_creazione
	 * @return  the value of covidus_t_intervento.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_intervento.data_creazione
	 * @param dataCreazione  the value for covidus_t_intervento.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_intervento.data_modifica
	 * @return  the value of covidus_t_intervento.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_intervento.data_modifica
	 * @param dataModifica  the value for covidus_t_intervento.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_intervento.data_cancellazione
	 * @return  the value of covidus_t_intervento.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_intervento.data_cancellazione
	 * @param dataCancellazione  the value for covidus_t_intervento.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}