package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidusTAdiCovid {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_adicovid.adicovid_id
	 * @mbg.generated
	 */
	private Integer adicovidId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_adicovid.adicovid_data_start
	 * @mbg.generated
	 */
	private Date adicovidDataStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_adicovid.adicovid_data_end
	 * @mbg.generated
	 */
	private Date adicovidDataEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_adicovid.adicovid_note
	 * @mbg.generated
	 */
	private String adicovidNote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_adicovid.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_adicovid.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_adicovid.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_adicovid.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_adicovid.adicovid_id
	 * @return  the value of covidus_t_adicovid.adicovid_id
	 * @mbg.generated
	 */
	public Integer getAdicovidId() {
		return adicovidId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_adicovid.adicovid_id
	 * @param adicovidId  the value for covidus_t_adicovid.adicovid_id
	 * @mbg.generated
	 */
	public void setAdicovidId(Integer adicovidId) {
		this.adicovidId = adicovidId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_adicovid.adicovid_data_start
	 * @return  the value of covidus_t_adicovid.adicovid_data_start
	 * @mbg.generated
	 */
	public Date getAdicovidDataStart() {
		return adicovidDataStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_adicovid.adicovid_data_start
	 * @param adicovidDataStart  the value for covidus_t_adicovid.adicovid_data_start
	 * @mbg.generated
	 */
	public void setAdicovidDataStart(Date adicovidDataStart) {
		this.adicovidDataStart = adicovidDataStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_adicovid.adicovid_data_end
	 * @return  the value of covidus_t_adicovid.adicovid_data_end
	 * @mbg.generated
	 */
	public Date getAdicovidDataEnd() {
		return adicovidDataEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_adicovid.adicovid_data_end
	 * @param adicovidDataEnd  the value for covidus_t_adicovid.adicovid_data_end
	 * @mbg.generated
	 */
	public void setAdicovidDataEnd(Date adicovidDataEnd) {
		this.adicovidDataEnd = adicovidDataEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_adicovid.adicovid_note
	 * @return  the value of covidus_t_adicovid.adicovid_note
	 * @mbg.generated
	 */
	public String getAdicovidNote() {
		return adicovidNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_adicovid.adicovid_note
	 * @param adicovidNote  the value for covidus_t_adicovid.adicovid_note
	 * @mbg.generated
	 */
	public void setAdicovidNote(String adicovidNote) {
		this.adicovidNote = adicovidNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_adicovid.utente_operazione
	 * @return  the value of covidus_t_adicovid.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_adicovid.utente_operazione
	 * @param utenteOperazione  the value for covidus_t_adicovid.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_adicovid.data_creazione
	 * @return  the value of covidus_t_adicovid.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_adicovid.data_creazione
	 * @param dataCreazione  the value for covidus_t_adicovid.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_adicovid.data_modifica
	 * @return  the value of covidus_t_adicovid.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_adicovid.data_modifica
	 * @param dataModifica  the value for covidus_t_adicovid.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_adicovid.data_cancellazione
	 * @return  the value of covidus_t_adicovid.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_adicovid.data_cancellazione
	 * @param dataCancellazione  the value for covidus_t_adicovid.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}