package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class CovidusTConsensoFarmaco {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_consenso_farmaco.consfarm_id
	 * @mbg.generated
	 */
	private Integer consfarmId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_consenso_farmaco.id_soggetto
	 * @mbg.generated
	 */
	private Long idSoggetto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_consenso_farmaco.cons_tipo_id
	 * @mbg.generated
	 */
	private Integer consTipoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_consenso_farmaco.farm_id
	 * @mbg.generated
	 */
	private Integer farmId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_consenso_farmaco.consfarm_data
	 * @mbg.generated
	 */
	private Date consfarmData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_consenso_farmaco.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_consenso_farmaco.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_consenso_farmaco.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column covidus_t_consenso_farmaco.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_consenso_farmaco.consfarm_id
	 * @return  the value of covidus_t_consenso_farmaco.consfarm_id
	 * @mbg.generated
	 */
	public Integer getConsfarmId() {
		return consfarmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_consenso_farmaco.consfarm_id
	 * @param consfarmId  the value for covidus_t_consenso_farmaco.consfarm_id
	 * @mbg.generated
	 */
	public void setConsfarmId(Integer consfarmId) {
		this.consfarmId = consfarmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_consenso_farmaco.id_soggetto
	 * @return  the value of covidus_t_consenso_farmaco.id_soggetto
	 * @mbg.generated
	 */
	public Long getIdSoggetto() {
		return idSoggetto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_consenso_farmaco.id_soggetto
	 * @param idSoggetto  the value for covidus_t_consenso_farmaco.id_soggetto
	 * @mbg.generated
	 */
	public void setIdSoggetto(Long idSoggetto) {
		this.idSoggetto = idSoggetto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_consenso_farmaco.cons_tipo_id
	 * @return  the value of covidus_t_consenso_farmaco.cons_tipo_id
	 * @mbg.generated
	 */
	public Integer getConsTipoId() {
		return consTipoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_consenso_farmaco.cons_tipo_id
	 * @param consTipoId  the value for covidus_t_consenso_farmaco.cons_tipo_id
	 * @mbg.generated
	 */
	public void setConsTipoId(Integer consTipoId) {
		this.consTipoId = consTipoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_consenso_farmaco.farm_id
	 * @return  the value of covidus_t_consenso_farmaco.farm_id
	 * @mbg.generated
	 */
	public Integer getFarmId() {
		return farmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_consenso_farmaco.farm_id
	 * @param farmId  the value for covidus_t_consenso_farmaco.farm_id
	 * @mbg.generated
	 */
	public void setFarmId(Integer farmId) {
		this.farmId = farmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_consenso_farmaco.consfarm_data
	 * @return  the value of covidus_t_consenso_farmaco.consfarm_data
	 * @mbg.generated
	 */
	public Date getConsfarmData() {
		return consfarmData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_consenso_farmaco.consfarm_data
	 * @param consfarmData  the value for covidus_t_consenso_farmaco.consfarm_data
	 * @mbg.generated
	 */
	public void setConsfarmData(Date consfarmData) {
		this.consfarmData = consfarmData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_consenso_farmaco.utente_operazione
	 * @return  the value of covidus_t_consenso_farmaco.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_consenso_farmaco.utente_operazione
	 * @param utenteOperazione  the value for covidus_t_consenso_farmaco.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_consenso_farmaco.data_creazione
	 * @return  the value of covidus_t_consenso_farmaco.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_consenso_farmaco.data_creazione
	 * @param dataCreazione  the value for covidus_t_consenso_farmaco.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_consenso_farmaco.data_modifica
	 * @return  the value of covidus_t_consenso_farmaco.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_consenso_farmaco.data_modifica
	 * @param dataModifica  the value for covidus_t_consenso_farmaco.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column covidus_t_consenso_farmaco.data_cancellazione
	 * @return  the value of covidus_t_consenso_farmaco.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column covidus_t_consenso_farmaco.data_cancellazione
	 * @param dataCancellazione  the value for covidus_t_consenso_farmaco.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}