package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class DNotificaAzione {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_azione.not_az_id
	 * @mbg.generated
	 */
	private Integer notAzId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_azione.not_az_cod
	 * @mbg.generated
	 */
	private String notAzCod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_azione.not_az_desc
	 * @mbg.generated
	 */
	private String notAzDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_azione.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_azione.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_azione.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_azione.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_azione.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_azione.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_azione.not_az_id
	 * @return  the value of d_notifica_azione.not_az_id
	 * @mbg.generated
	 */
	public Integer getNotAzId() {
		return notAzId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_azione.not_az_id
	 * @param notAzId  the value for d_notifica_azione.not_az_id
	 * @mbg.generated
	 */
	public void setNotAzId(Integer notAzId) {
		this.notAzId = notAzId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_azione.not_az_cod
	 * @return  the value of d_notifica_azione.not_az_cod
	 * @mbg.generated
	 */
	public String getNotAzCod() {
		return notAzCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_azione.not_az_cod
	 * @param notAzCod  the value for d_notifica_azione.not_az_cod
	 * @mbg.generated
	 */
	public void setNotAzCod(String notAzCod) {
		this.notAzCod = notAzCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_azione.not_az_desc
	 * @return  the value of d_notifica_azione.not_az_desc
	 * @mbg.generated
	 */
	public String getNotAzDesc() {
		return notAzDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_azione.not_az_desc
	 * @param notAzDesc  the value for d_notifica_azione.not_az_desc
	 * @mbg.generated
	 */
	public void setNotAzDesc(String notAzDesc) {
		this.notAzDesc = notAzDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_azione.validita_inizio
	 * @return  the value of d_notifica_azione.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_azione.validita_inizio
	 * @param validitaInizio  the value for d_notifica_azione.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_azione.validita_fine
	 * @return  the value of d_notifica_azione.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_azione.validita_fine
	 * @param validitaFine  the value for d_notifica_azione.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_azione.utente_operazione
	 * @return  the value of d_notifica_azione.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_azione.utente_operazione
	 * @param utenteOperazione  the value for d_notifica_azione.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_azione.data_creazione
	 * @return  the value of d_notifica_azione.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_azione.data_creazione
	 * @param dataCreazione  the value for d_notifica_azione.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_azione.data_modifica
	 * @return  the value of d_notifica_azione.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_azione.data_modifica
	 * @param dataModifica  the value for d_notifica_azione.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_azione.data_cancellazione
	 * @return  the value of d_notifica_azione.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_azione.data_cancellazione
	 * @param dataCancellazione  the value for d_notifica_azione.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}