package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class DNotificaEvento {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_evento.not_ev_id
	 * @mbg.generated
	 */
	private Integer notEvId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_evento.not_ev_cod
	 * @mbg.generated
	 */
	private String notEvCod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_evento.not_ev_desc
	 * @mbg.generated
	 */
	private String notEvDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_evento.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_evento.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_evento.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_evento.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_evento.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_notifica_evento.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_evento.not_ev_id
	 * @return  the value of d_notifica_evento.not_ev_id
	 * @mbg.generated
	 */
	public Integer getNotEvId() {
		return notEvId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_evento.not_ev_id
	 * @param notEvId  the value for d_notifica_evento.not_ev_id
	 * @mbg.generated
	 */
	public void setNotEvId(Integer notEvId) {
		this.notEvId = notEvId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_evento.not_ev_cod
	 * @return  the value of d_notifica_evento.not_ev_cod
	 * @mbg.generated
	 */
	public String getNotEvCod() {
		return notEvCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_evento.not_ev_cod
	 * @param notEvCod  the value for d_notifica_evento.not_ev_cod
	 * @mbg.generated
	 */
	public void setNotEvCod(String notEvCod) {
		this.notEvCod = notEvCod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_evento.not_ev_desc
	 * @return  the value of d_notifica_evento.not_ev_desc
	 * @mbg.generated
	 */
	public String getNotEvDesc() {
		return notEvDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_evento.not_ev_desc
	 * @param notEvDesc  the value for d_notifica_evento.not_ev_desc
	 * @mbg.generated
	 */
	public void setNotEvDesc(String notEvDesc) {
		this.notEvDesc = notEvDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_evento.validita_inizio
	 * @return  the value of d_notifica_evento.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_evento.validita_inizio
	 * @param validitaInizio  the value for d_notifica_evento.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_evento.validita_fine
	 * @return  the value of d_notifica_evento.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_evento.validita_fine
	 * @param validitaFine  the value for d_notifica_evento.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_evento.utente_operazione
	 * @return  the value of d_notifica_evento.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_evento.utente_operazione
	 * @param utenteOperazione  the value for d_notifica_evento.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_evento.data_creazione
	 * @return  the value of d_notifica_evento.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_evento.data_creazione
	 * @param dataCreazione  the value for d_notifica_evento.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_evento.data_modifica
	 * @return  the value of d_notifica_evento.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_evento.data_modifica
	 * @param dataModifica  the value for d_notifica_evento.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_notifica_evento.data_cancellazione
	 * @return  the value of d_notifica_evento.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_notifica_evento.data_cancellazione
	 * @param dataCancellazione  the value for d_notifica_evento.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}