package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

public class EsitoDimissioni {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column esito_dimissioni.id_dimiss
	 * @mbg.generated
	 */
	private Long idDimiss;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column esito_dimissioni.esito_dim
	 * @mbg.generated
	 */
	private String esitoDim;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column esito_dimissioni.id_dimiss
	 * @return  the value of esito_dimissioni.id_dimiss
	 * @mbg.generated
	 */
	public Long getIdDimiss() {
		return idDimiss;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column esito_dimissioni.id_dimiss
	 * @param idDimiss  the value for esito_dimissioni.id_dimiss
	 * @mbg.generated
	 */
	public void setIdDimiss(Long idDimiss) {
		this.idDimiss = idDimiss;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column esito_dimissioni.esito_dim
	 * @return  the value of esito_dimissioni.esito_dim
	 * @mbg.generated
	 */
	public String getEsitoDim() {
		return esitoDim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column esito_dimissioni.esito_dim
	 * @param esitoDim  the value for esito_dimissioni.esito_dim
	 * @mbg.generated
	 */
	public void setEsitoDim(String esitoDim) {
		this.esitoDim = esitoDim;
	}
}