package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

public class MedicoUsca {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medico_usca.id_medico
	 * @mbg.generated
	 */
	private Integer idMedico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medico_usca.cf_medico
	 * @mbg.generated
	 */
	private String cfMedico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medico_usca.codice_reg
	 * @mbg.generated
	 */
	private String codiceReg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medico_usca.cognome
	 * @mbg.generated
	 */
	private String cognome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column medico_usca.nome
	 * @mbg.generated
	 */
	private String nome;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medico_usca.id_medico
	 * @return  the value of medico_usca.id_medico
	 * @mbg.generated
	 */
	public Integer getIdMedico() {
		return idMedico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medico_usca.id_medico
	 * @param idMedico  the value for medico_usca.id_medico
	 * @mbg.generated
	 */
	public void setIdMedico(Integer idMedico) {
		this.idMedico = idMedico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medico_usca.cf_medico
	 * @return  the value of medico_usca.cf_medico
	 * @mbg.generated
	 */
	public String getCfMedico() {
		return cfMedico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medico_usca.cf_medico
	 * @param cfMedico  the value for medico_usca.cf_medico
	 * @mbg.generated
	 */
	public void setCfMedico(String cfMedico) {
		this.cfMedico = cfMedico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medico_usca.codice_reg
	 * @return  the value of medico_usca.codice_reg
	 * @mbg.generated
	 */
	public String getCodiceReg() {
		return codiceReg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medico_usca.codice_reg
	 * @param codiceReg  the value for medico_usca.codice_reg
	 * @mbg.generated
	 */
	public void setCodiceReg(String codiceReg) {
		this.codiceReg = codiceReg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medico_usca.cognome
	 * @return  the value of medico_usca.cognome
	 * @mbg.generated
	 */
	public String getCognome() {
		return cognome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medico_usca.cognome
	 * @param cognome  the value for medico_usca.cognome
	 * @mbg.generated
	 */
	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column medico_usca.nome
	 * @return  the value of medico_usca.nome
	 * @mbg.generated
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column medico_usca.nome
	 * @param nome  the value for medico_usca.nome
	 * @mbg.generated
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}
}