package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

public class RepartoRicovero {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reparto_ricovero.id_rep_ricovero
	 * @mbg.generated
	 */
	private Long idRepRicovero;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reparto_ricovero.reparto_ricovero
	 * @mbg.generated
	 */
	private String repartoRicovero;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reparto_ricovero.id_rep_ricovero
	 * @return  the value of reparto_ricovero.id_rep_ricovero
	 * @mbg.generated
	 */
	public Long getIdRepRicovero() {
		return idRepRicovero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reparto_ricovero.id_rep_ricovero
	 * @param idRepRicovero  the value for reparto_ricovero.id_rep_ricovero
	 * @mbg.generated
	 */
	public void setIdRepRicovero(Long idRepRicovero) {
		this.idRepRicovero = idRepRicovero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reparto_ricovero.reparto_ricovero
	 * @return  the value of reparto_ricovero.reparto_ricovero
	 * @mbg.generated
	 */
	public String getRepartoRicovero() {
		return repartoRicovero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reparto_ricovero.reparto_ricovero
	 * @param repartoRicovero  the value for reparto_ricovero.reparto_ricovero
	 * @mbg.generated
	 */
	public void setRepartoRicovero(String repartoRicovero) {
		this.repartoRicovero = repartoRicovero;
	}
}