package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

public class RUtenteEnte {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_utente_ente.cf_utente
	 * @mbg.generated
	 */
	private String cfUtente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_utente_ente.id_ente
	 * @mbg.generated
	 */
	private Integer idEnte;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_utente_ente.cf_utente
	 * @return  the value of r_utente_ente.cf_utente
	 * @mbg.generated
	 */
	public String getCfUtente() {
		return cfUtente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_utente_ente.cf_utente
	 * @param cfUtente  the value for r_utente_ente.cf_utente
	 * @mbg.generated
	 */
	public void setCfUtente(String cfUtente) {
		this.cfUtente = cfUtente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_utente_ente.id_ente
	 * @return  the value of r_utente_ente.id_ente
	 * @mbg.generated
	 */
	public Integer getIdEnte() {
		return idEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_utente_ente.id_ente
	 * @param idEnte  the value for r_utente_ente.id_ente
	 * @mbg.generated
	 */
	public void setIdEnte(Integer idEnte) {
		this.idEnte = idEnte;
	}
}