package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

public class Sindaco {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sindaco.cf_utente
     *
     * @mbg.generated
     */
    private String cfUtente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sindaco.comune_istat
     *
     * @mbg.generated
     */
    private String comuneIstat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sindaco.cognome
     *
     * @mbg.generated
     */
    private String cognome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sindaco.nome
     *
     * @mbg.generated
     */
    private String nome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sindaco.telefono
     *
     * @mbg.generated
     */
    private String telefono;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sindaco.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sindaco.cf_utente
     *
     * @return the value of sindaco.cf_utente
     *
     * @mbg.generated
     */
    public String getCfUtente() {
        return cfUtente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sindaco.cf_utente
     *
     * @param cfUtente the value for sindaco.cf_utente
     *
     * @mbg.generated
     */
    public void setCfUtente(String cfUtente) {
        this.cfUtente = cfUtente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sindaco.comune_istat
     *
     * @return the value of sindaco.comune_istat
     *
     * @mbg.generated
     */
    public String getComuneIstat() {
        return comuneIstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sindaco.comune_istat
     *
     * @param comuneIstat the value for sindaco.comune_istat
     *
     * @mbg.generated
     */
    public void setComuneIstat(String comuneIstat) {
        this.comuneIstat = comuneIstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sindaco.cognome
     *
     * @return the value of sindaco.cognome
     *
     * @mbg.generated
     */
    public String getCognome() {
        return cognome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sindaco.cognome
     *
     * @param cognome the value for sindaco.cognome
     *
     * @mbg.generated
     */
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sindaco.nome
     *
     * @return the value of sindaco.nome
     *
     * @mbg.generated
     */
    public String getNome() {
        return nome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sindaco.nome
     *
     * @param nome the value for sindaco.nome
     *
     * @mbg.generated
     */
    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sindaco.telefono
     *
     * @return the value of sindaco.telefono
     *
     * @mbg.generated
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sindaco.telefono
     *
     * @param telefono the value for sindaco.telefono
     *
     * @mbg.generated
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sindaco.email
     *
     * @return the value of sindaco.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sindaco.email
     *
     * @param email the value for sindaco.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }
}