package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class SoggettoContatto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_soggetto_contatti.id_soggetto_contatti
     *
     * @mbg.generated
     */
    private Integer idSoggettoContatti;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_soggetto_contatti.id_soggetto_da
     *
     * @mbg.generated
     */
    private Long idSoggettoDa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_soggetto_contatti.id_soggetto_a
     *
     * @mbg.generated
     */
    private Long idSoggettoA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_soggetto_contatti.note_contatto
     *
     * @mbg.generated
     */
    private String noteContatto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_soggetto_contatti.id_decorso
     *
     * @mbg.generated
     */
    private Long idDecorso;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_soggetto_contatti.contatto_tipo_id
     *
     * @mbg.generated
     */
    private Long contattoTipoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_soggetto_contatti.validita_inizio
     *
     * @mbg.generated
     */
    private Date validitaInizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_soggetto_contatti.validita_fine
     *
     * @mbg.generated
     */
    private Date validitaFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_soggetto_contatti.utente_operazione
     *
     * @mbg.generated
     */
    private String utenteOperazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_soggetto_contatti.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_soggetto_contatti.data_modifca
     *
     * @mbg.generated
     */
    private Date dataModifca;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_soggetto_contatti.data_cancellazione
     *
     * @mbg.generated
     */
    private Date dataCancellazione;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_soggetto_contatti.id_soggetto_contatti
     *
     * @return the value of r_soggetto_contatti.id_soggetto_contatti
     *
     * @mbg.generated
     */
    public Integer getIdSoggettoContatti() {
        return idSoggettoContatti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_soggetto_contatti.id_soggetto_contatti
     *
     * @param idSoggettoContatti the value for r_soggetto_contatti.id_soggetto_contatti
     *
     * @mbg.generated
     */
    public void setIdSoggettoContatti(Integer idSoggettoContatti) {
        this.idSoggettoContatti = idSoggettoContatti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_soggetto_contatti.id_soggetto_da
     *
     * @return the value of r_soggetto_contatti.id_soggetto_da
     *
     * @mbg.generated
     */
    public Long getIdSoggettoDa() {
        return idSoggettoDa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_soggetto_contatti.id_soggetto_da
     *
     * @param idSoggettoDa the value for r_soggetto_contatti.id_soggetto_da
     *
     * @mbg.generated
     */
    public void setIdSoggettoDa(Long idSoggettoDa) {
        this.idSoggettoDa = idSoggettoDa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_soggetto_contatti.id_soggetto_a
     *
     * @return the value of r_soggetto_contatti.id_soggetto_a
     *
     * @mbg.generated
     */
    public Long getIdSoggettoA() {
        return idSoggettoA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_soggetto_contatti.id_soggetto_a
     *
     * @param idSoggettoA the value for r_soggetto_contatti.id_soggetto_a
     *
     * @mbg.generated
     */
    public void setIdSoggettoA(Long idSoggettoA) {
        this.idSoggettoA = idSoggettoA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_soggetto_contatti.note_contatto
     *
     * @return the value of r_soggetto_contatti.note_contatto
     *
     * @mbg.generated
     */
    public String getNoteContatto() {
        return noteContatto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_soggetto_contatti.note_contatto
     *
     * @param noteContatto the value for r_soggetto_contatti.note_contatto
     *
     * @mbg.generated
     */
    public void setNoteContatto(String noteContatto) {
        this.noteContatto = noteContatto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_soggetto_contatti.id_decorso
     *
     * @return the value of r_soggetto_contatti.id_decorso
     *
     * @mbg.generated
     */
    public Long getIdDecorso() {
        return idDecorso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_soggetto_contatti.id_decorso
     *
     * @param idDecorso the value for r_soggetto_contatti.id_decorso
     *
     * @mbg.generated
     */
    public void setIdDecorso(Long idDecorso) {
        this.idDecorso = idDecorso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_soggetto_contatti.contatto_tipo_id
     *
     * @return the value of r_soggetto_contatti.contatto_tipo_id
     *
     * @mbg.generated
     */
    public Long getContattoTipoId() {
        return contattoTipoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_soggetto_contatti.contatto_tipo_id
     *
     * @param contattoTipoId the value for r_soggetto_contatti.contatto_tipo_id
     *
     * @mbg.generated
     */
    public void setContattoTipoId(Long contattoTipoId) {
        this.contattoTipoId = contattoTipoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_soggetto_contatti.validita_inizio
     *
     * @return the value of r_soggetto_contatti.validita_inizio
     *
     * @mbg.generated
     */
    public Date getValiditaInizio() {
        return validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_soggetto_contatti.validita_inizio
     *
     * @param validitaInizio the value for r_soggetto_contatti.validita_inizio
     *
     * @mbg.generated
     */
    public void setValiditaInizio(Date validitaInizio) {
        this.validitaInizio = validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_soggetto_contatti.validita_fine
     *
     * @return the value of r_soggetto_contatti.validita_fine
     *
     * @mbg.generated
     */
    public Date getValiditaFine() {
        return validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_soggetto_contatti.validita_fine
     *
     * @param validitaFine the value for r_soggetto_contatti.validita_fine
     *
     * @mbg.generated
     */
    public void setValiditaFine(Date validitaFine) {
        this.validitaFine = validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_soggetto_contatti.utente_operazione
     *
     * @return the value of r_soggetto_contatti.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_soggetto_contatti.utente_operazione
     *
     * @param utenteOperazione the value for r_soggetto_contatti.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_soggetto_contatti.data_creazione
     *
     * @return the value of r_soggetto_contatti.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_soggetto_contatti.data_creazione
     *
     * @param dataCreazione the value for r_soggetto_contatti.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_soggetto_contatti.data_modifca
     *
     * @return the value of r_soggetto_contatti.data_modifca
     *
     * @mbg.generated
     */
    public Date getDataModifca() {
        return dataModifca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_soggetto_contatti.data_modifca
     *
     * @param dataModifca the value for r_soggetto_contatti.data_modifca
     *
     * @mbg.generated
     */
    public void setDataModifca(Date dataModifca) {
        this.dataModifca = dataModifca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_soggetto_contatti.data_cancellazione
     *
     * @return the value of r_soggetto_contatti.data_cancellazione
     *
     * @mbg.generated
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_soggetto_contatti.data_cancellazione
     *
     * @param dataCancellazione the value for r_soggetto_contatti.data_cancellazione
     *
     * @mbg.generated
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }
}