package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

import java.util.Date;

public class Tampone {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_tampone
	 * @mbg.generated
	 */
	private Long idTampone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_soggetto
	 * @mbg.generated
	 */
	private Long idSoggetto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_laboratorio
	 * @mbg.generated
	 */
	private Long idLaboratorio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.criterio_epidemiologico_covid19
	 * @mbg.generated
	 */
	private String criterioEpidemiologicoCovid19;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_test_covid
	 * @mbg.generated
	 */
	private Long idTestCovid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.id_ris_tamp
	 * @mbg.generated
	 */
	private Long idRisTamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.tampone_autorizzato
	 * @mbg.generated
	 */
	private String tamponeAutorizzato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.data_inserimento_richiesta
	 * @mbg.generated
	 */
	private Date dataInserimentoRichiesta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.data_ultima_modifica
	 * @mbg.generated
	 */
	private Date dataUltimaModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.utente_ultima_modifica
	 * @mbg.generated
	 */
	private String utenteUltimaModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.data_test
	 * @mbg.generated
	 */
	private Date dataTest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.medico_richiedente
	 * @mbg.generated
	 */
	private String medicoRichiedente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tampone.contatto_richiedente
	 * @mbg.generated
	 */
	private String contattoRichiedente;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_tampone
	 * @return  the value of tampone.id_tampone
	 * @mbg.generated
	 */
	public Long getIdTampone() {
		return idTampone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_tampone
	 * @param idTampone  the value for tampone.id_tampone
	 * @mbg.generated
	 */
	public void setIdTampone(Long idTampone) {
		this.idTampone = idTampone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_soggetto
	 * @return  the value of tampone.id_soggetto
	 * @mbg.generated
	 */
	public Long getIdSoggetto() {
		return idSoggetto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_soggetto
	 * @param idSoggetto  the value for tampone.id_soggetto
	 * @mbg.generated
	 */
	public void setIdSoggetto(Long idSoggetto) {
		this.idSoggetto = idSoggetto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_laboratorio
	 * @return  the value of tampone.id_laboratorio
	 * @mbg.generated
	 */
	public Long getIdLaboratorio() {
		return idLaboratorio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_laboratorio
	 * @param idLaboratorio  the value for tampone.id_laboratorio
	 * @mbg.generated
	 */
	public void setIdLaboratorio(Long idLaboratorio) {
		this.idLaboratorio = idLaboratorio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.criterio_epidemiologico_covid19
	 * @return  the value of tampone.criterio_epidemiologico_covid19
	 * @mbg.generated
	 */
	public String getCriterioEpidemiologicoCovid19() {
		return criterioEpidemiologicoCovid19;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.criterio_epidemiologico_covid19
	 * @param criterioEpidemiologicoCovid19  the value for tampone.criterio_epidemiologico_covid19
	 * @mbg.generated
	 */
	public void setCriterioEpidemiologicoCovid19(String criterioEpidemiologicoCovid19) {
		this.criterioEpidemiologicoCovid19 = criterioEpidemiologicoCovid19;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_test_covid
	 * @return  the value of tampone.id_test_covid
	 * @mbg.generated
	 */
	public Long getIdTestCovid() {
		return idTestCovid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_test_covid
	 * @param idTestCovid  the value for tampone.id_test_covid
	 * @mbg.generated
	 */
	public void setIdTestCovid(Long idTestCovid) {
		this.idTestCovid = idTestCovid;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.id_ris_tamp
	 * @return  the value of tampone.id_ris_tamp
	 * @mbg.generated
	 */
	public Long getIdRisTamp() {
		return idRisTamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.id_ris_tamp
	 * @param idRisTamp  the value for tampone.id_ris_tamp
	 * @mbg.generated
	 */
	public void setIdRisTamp(Long idRisTamp) {
		this.idRisTamp = idRisTamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.tampone_autorizzato
	 * @return  the value of tampone.tampone_autorizzato
	 * @mbg.generated
	 */
	public String getTamponeAutorizzato() {
		return tamponeAutorizzato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.tampone_autorizzato
	 * @param tamponeAutorizzato  the value for tampone.tampone_autorizzato
	 * @mbg.generated
	 */
	public void setTamponeAutorizzato(String tamponeAutorizzato) {
		this.tamponeAutorizzato = tamponeAutorizzato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.data_inserimento_richiesta
	 * @return  the value of tampone.data_inserimento_richiesta
	 * @mbg.generated
	 */
	public Date getDataInserimentoRichiesta() {
		return dataInserimentoRichiesta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.data_inserimento_richiesta
	 * @param dataInserimentoRichiesta  the value for tampone.data_inserimento_richiesta
	 * @mbg.generated
	 */
	public void setDataInserimentoRichiesta(Date dataInserimentoRichiesta) {
		this.dataInserimentoRichiesta = dataInserimentoRichiesta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.data_ultima_modifica
	 * @return  the value of tampone.data_ultima_modifica
	 * @mbg.generated
	 */
	public Date getDataUltimaModifica() {
		return dataUltimaModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.data_ultima_modifica
	 * @param dataUltimaModifica  the value for tampone.data_ultima_modifica
	 * @mbg.generated
	 */
	public void setDataUltimaModifica(Date dataUltimaModifica) {
		this.dataUltimaModifica = dataUltimaModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.utente_ultima_modifica
	 * @return  the value of tampone.utente_ultima_modifica
	 * @mbg.generated
	 */
	public String getUtenteUltimaModifica() {
		return utenteUltimaModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.utente_ultima_modifica
	 * @param utenteUltimaModifica  the value for tampone.utente_ultima_modifica
	 * @mbg.generated
	 */
	public void setUtenteUltimaModifica(String utenteUltimaModifica) {
		this.utenteUltimaModifica = utenteUltimaModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.data_test
	 * @return  the value of tampone.data_test
	 * @mbg.generated
	 */
	public Date getDataTest() {
		return dataTest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.data_test
	 * @param dataTest  the value for tampone.data_test
	 * @mbg.generated
	 */
	public void setDataTest(Date dataTest) {
		this.dataTest = dataTest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.medico_richiedente
	 * @return  the value of tampone.medico_richiedente
	 * @mbg.generated
	 */
	public String getMedicoRichiedente() {
		return medicoRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.medico_richiedente
	 * @param medicoRichiedente  the value for tampone.medico_richiedente
	 * @mbg.generated
	 */
	public void setMedicoRichiedente(String medicoRichiedente) {
		this.medicoRichiedente = medicoRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tampone.contatto_richiedente
	 * @return  the value of tampone.contatto_richiedente
	 * @mbg.generated
	 */
	public String getContattoRichiedente() {
		return contattoRichiedente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tampone.contatto_richiedente
	 * @param contattoRichiedente  the value for tampone.contatto_richiedente
	 * @mbg.generated
	 */
	public void setContattoRichiedente(String contattoRichiedente) {
		this.contattoRichiedente = contattoRichiedente;
	}
}