package it.csi.gescovid.uscammgapi.business.be.impl.mapper.dto;

public class UtenteContatto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column utente_contatto.cf_utente
	 * @mbg.generated
	 */
	private String cfUtente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column utente_contatto.nome
	 * @mbg.generated
	 */
	private String nome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column utente_contatto.cognome
	 * @mbg.generated
	 */
	private String cognome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column utente_contatto.telefono
	 * @mbg.generated
	 */
	private String telefono;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column utente_contatto.email
	 * @mbg.generated
	 */
	private String email;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column utente_contatto.cf_utente
	 * @return  the value of utente_contatto.cf_utente
	 * @mbg.generated
	 */
	public String getCfUtente() {
		return cfUtente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column utente_contatto.cf_utente
	 * @param cfUtente  the value for utente_contatto.cf_utente
	 * @mbg.generated
	 */
	public void setCfUtente(String cfUtente) {
		this.cfUtente = cfUtente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column utente_contatto.nome
	 * @return  the value of utente_contatto.nome
	 * @mbg.generated
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column utente_contatto.nome
	 * @param nome  the value for utente_contatto.nome
	 * @mbg.generated
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column utente_contatto.cognome
	 * @return  the value of utente_contatto.cognome
	 * @mbg.generated
	 */
	public String getCognome() {
		return cognome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column utente_contatto.cognome
	 * @param cognome  the value for utente_contatto.cognome
	 * @mbg.generated
	 */
	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column utente_contatto.telefono
	 * @return  the value of utente_contatto.telefono
	 * @mbg.generated
	 */
	public String getTelefono() {
		return telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column utente_contatto.telefono
	 * @param telefono  the value for utente_contatto.telefono
	 * @mbg.generated
	 */
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column utente_contatto.email
	 * @return  the value of utente_contatto.email
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column utente_contatto.email
	 * @param email  the value for utente_contatto.email
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email;
	}
}